#!/usr/bin/env bash

new_ext='.webm'

# Colours
[[ -t 1 ]] && {
    c_d=$'\e[1;30m' # GREY
    c_r=$'\e[1;31m' # RED
    c_g=$'\e[1;32m' # GREEN
    c_y=$'\e[1;33m' # YELLOW
    c_b=$'\e[1;34m' # BLUE
    c_m=$'\e[1;35m' # VIOLET
    c_t=$'\e[1;36m' # TEAL
    c_w=$'\e[1;37m' # WHITE
    c_c=$'\e[0m'    # DISABLES COLOUR
}

function help {
    script_name="${0//*\/}"
    printf '\n%s\n\n'      "${c_w}Convert mp4 videos to webm with ffmpeg$c_c"
    printf '%s\n'          "${c_b}SYNOPSIS$c_c"
    printf '  %s\n'        "$c_y$script_name ${c_d}[${c_r}QUALITY$c_d]$c_c"
    printf '  %s\n\n'      "$c_y$script_name $c_w-h$c_d|$c_w--help$c_c"
    printf '%s\n'          "${c_b}EXAMPLES$c_c"
    printf '  %-26s%s\n'   "$c_y$script_name$c_c" 'Convert all files in current directory with their autodetected bitrates'
    printf '  %-33s%s\n\n' "$c_y$script_name ${c_w}1.5$c_c" 'Convert all files in current directory with 1.5 times their autodetected bitrates'
}

function error {
    printf '%s %s\n' "${c_r}ERROR:$c_c" "$c_w$1$c_c" >&2
    exit 1
}

function convert_mp4 {
    # Figure out number of cores
    if [[ "$(uname)" = 'Darwin' ]]; then
        num_cores="$(sysctl -n hw.ncpu)"
    elif [[ "$(uname)" =~ Linux ]]; then
        while read -r; do
            [[ "$REPLY" =~ ^processor[^:]*:[^0-9]*([0-9][0-9]*) ]] && {
                num_cores="${BASH_REMATCH[1]}"
                num_cores=$(( num_cores + 1 ))
            }
        done < /proc/cpuinfo
    else
        num_cores=1
    fi

    printf '%s %s\n' "$c_b==>" "$c_w$num_cores cores detected$c_c"

    # Check and see if the folder "converting" exists. If it doesn't then we want to create it.
    [[ -d converting ]] || install -d converting

    # Store the filename then drop it from $@
    filename="$1"
    shift

    # Determine old extension
    old_ext="${filename/*\.}"

    # Determine new filename
    new_file="${filename/\.${old_ext}}${new_ext}"

    # Convert video
    ffmpeg -i "$filename" -c:v libvpx -crf 32 -q:v 10 -b:v 0 -c:a libvorbis -threads "$num_cores" "$@" -pass 1 -y -f webm /dev/null
    ffmpeg -i "$filename" -c:v libvpx -crf 36 -q:v 10 -b:v 0 -c:a libvorbis -threads "$num_cores" "$@" -pass 2 "converting/$new_file"
    [[ -f ffmpeg2pass-0.log ]] && rm ffmpeg2pass-0.log

    # Move new webm files into "created" folder
    mkclean --doctype 4 --keep-cues --optimize "converting/$new_file" "$new_file"

    # Remove the converting file and directory
    rm "converting/$new_file"
    rmdir converting
}

type -P ffmpeg >/dev/null \
    || error 'The ffmpeg executable was not found in $PATH'

type -P mkclean >/dev/null \
    || error 'The mkclean executable was not found in $PATH'

[[ "$1" = '-h' || "$1" = '--help' ]] && {
    help
    exit 0
}

if [[ -n "$1" ]]; then
    bitrate_multiple="$1"
else
    bitrate_multiple=1
fi

for video in *.mp4; do
    convert_mp4 "$video" "$@"
done
